{
  "x-generator": "NSwag v13.6.0.0 (NJsonSchema v10.1.18.0 (Newtonsoft.Json v12.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "MSR API",
    "description": "REST API Answer 3",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://73268cc5edeb.ngrok.io"
    }
  ],
  "paths": {
    "/v{version}/Account/login": {
      "post": {
        "tags": [
          "Account"
        ],
        "operationId": "Account_Login",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SystemLoginRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfString"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/Account/forgotpassword": {
      "post": {
        "tags": [
          "Account"
        ],
        "operationId": "Account_ForgotPassword",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ForgotPasswordRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/Account/forgotusername": {
      "post": {
        "tags": [
          "Account"
        ],
        "operationId": "Account_ForgotUserName",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ForgotUserNameRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/Account/resetpassword": {
      "patch": {
        "tags": [
          "Account"
        ],
        "operationId": "Account_ResetPassword",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResetPasswordRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "404": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/Location": {
      "get": {
        "tags": [
          "Location"
        ],
        "operationId": "Location_Get",
        "parameters": [
          {
            "name": "ParentId",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfLocation"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/Menu": {
      "get": {
        "tags": [
          "Menu"
        ],
        "operationId": "Menu_GetMenu",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfBoolean"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/Part": {
      "get": {
        "tags": [
          "Part"
        ],
        "operationId": "Part_GetParts",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfBoolean"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/Role": {
      "post": {
        "tags": [
          "Role"
        ],
        "operationId": "Role_CreateMenuRoleMap",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateMenuRoleMapRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResult"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Role"
        ],
        "operationId": "Role_GetRoles",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfICollectionOfRole"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Role"
        ],
        "operationId": "Role_AddPermissionsToMenuRoleMap",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateMenuRoleMapRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "204": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/Role/{id}": {
      "delete": {
        "tags": [
          "Role"
        ],
        "operationId": "Role_RemoveMenuRoleMap",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2147483647
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResult"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/User": {
      "get": {
        "tags": [
          "User"
        ],
        "operationId": "User_GetUsers",
        "parameters": [
          {
            "name": "Id",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "FirstName",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          },
          {
            "name": "LastName",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 3
          },
          {
            "name": "UserName",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 4
          },
          {
            "name": "Title",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 5
          },
          {
            "name": "Supervisor",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            },
            "x-position": 6
          },
          {
            "name": "PrimaryPhone",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 7
          },
          {
            "name": "Email",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 8
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 9
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfICollectionOfUser"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "User"
        ],
        "operationId": "User_CreateUser",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfUser"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "User"
        ],
        "operationId": "User_UpdateUser",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfUser"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/User/LoggedInUser": {
      "get": {
        "tags": [
          "User"
        ],
        "operationId": "User_GetLoggedInUserData",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfUser"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/User/{accountId}": {
      "delete": {
        "tags": [
          "User"
        ],
        "operationId": "User_DeactivateUser",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2147483647
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "401": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/Workflow/pending": {
      "get": {
        "tags": [
          "Workflow"
        ],
        "operationId": "Workflow_GetPendingApprovals",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfPendingApprovalNotification"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/WorkflowGroup": {
      "get": {
        "tags": [
          "WorkflowGroup"
        ],
        "operationId": "WorkflowGroup_Get",
        "parameters": [
          {
            "name": "Id",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfICollectionOfWorkflowGroupModel"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "WorkflowGroup"
        ],
        "operationId": "WorkflowGroup_Post",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateWorkflowGroupRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfWorkflowGroupModel"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "WorkflowGroup"
        ],
        "operationId": "WorkflowGroup_Update",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateWorkflowGroupRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfWorkflowGroupModel"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/WorkflowGroup/{workflowId}": {
      "delete": {
        "tags": [
          "WorkflowGroup"
        ],
        "operationId": "WorkflowGroup_Delete",
        "parameters": [
          {
            "name": "workflowId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2147483647
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "204": {
            "description": ""
          }
        }
      }
    },
    "/v{version}/WorkflowStage": {
      "get": {
        "tags": [
          "WorkflowStage"
        ],
        "operationId": "WorkflowStage_Get",
        "parameters": [
          {
            "name": "Id",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfICollectionOfWorkflowStageModel"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "WorkflowStage"
        ],
        "operationId": "WorkflowStage_Post",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateWorkflowStageRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfWorkflowStageModel"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "WorkflowStage"
        ],
        "operationId": "WorkflowStage_Update",
        "parameters": [
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "requestBody": {
          "x-name": "request",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateWorkflowStageRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuditActionResultOfWorkflowStageModel"
                }
              }
            }
          }
        }
      }
    },
    "/v{version}/WorkflowStage/{workflowId}": {
      "delete": {
        "tags": [
          "WorkflowStage"
        ],
        "operationId": "WorkflowStage_Delete",
        "parameters": [
          {
            "name": "workflowId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2147483647
            },
            "x-position": 1
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "example": "1"
            },
            "x-position": 2
          }
        ],
        "responses": {
          "204": {
            "description": ""
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AuditActionResultOfString": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "string",
                "nullable": true
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "AuditActionResult": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "successMessage": {
            "type": "string",
            "nullable": true
          },
          "errorMessages": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/ErrorMessage"
            }
          },
          "returnedObject": {
            "nullable": true
          },
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "hasErrors": {
            "type": "boolean"
          },
          "hasValidationErrors": {
            "type": "boolean"
          }
        }
      },
      "ErrorMessage": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "number": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "isValidationMessage": {
            "type": "boolean"
          }
        }
      },
      "SystemLoginRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "userName",
          "password"
        ],
        "properties": {
          "userName": {
            "type": "string",
            "minLength": 1
          },
          "password": {
            "type": "string",
            "minLength": 1
          }
        },
        "example": {
            "userName": "dummy",
            "password": "dummy"
        }
      },
      "ForgotPasswordRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "userName"
        ],
        "properties": {
          "userName": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "ForgotUserNameRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "ResetPasswordRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "token",
          "newPassword"
        ],
        "properties": {
          "token": {
            "type": "string",
            "minLength": 1
          },
          "newPassword": {
            "type": "string",
            "minLength": 1
          }
        },
        "example": {
            "token": "kvcNhL+3YY5K4WfYNxC31POQcgSvdpsnSgrsfqeAncE=",
            "newPassword": "dummy"
        }
      },
      "AuditActionResultOfLocation": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "array",
                "nullable": true,
                "items": {
                    "$ref": "#/components/schemas/Location"
                }
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "Location": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "oldId": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "address1": {
            "type": "string",
            "nullable": true
          },
          "address2": {
            "type": "string",
            "nullable": true
          },
          "city": {
            "type": "string",
            "nullable": true
          },
          "state": {
            "type": "string",
            "nullable": true
          },
          "postalCode": {
            "type": "string",
            "nullable": true
          },
          "country": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "parentId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "internalAddress": {
            "type": "string",
            "nullable": true
          },
          "invoiceClass": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "AuditActionResultOfBoolean": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "boolean"
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "CreateMenuRoleMapRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "menuId",
          "roleId"
        ],
        "properties": {
          "menuId": {
            "type": "integer",
            "format": "int32"
          },
          "roleId": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
            "menuId": 2147483647,
            "roleId": 2147483647
        }
      },
      "AuditActionResultOfICollectionOfRole": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "array",
                "nullable": true,
                "items": {
                  "$ref": "#/components/schemas/Role"
                }
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "Role": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "isCertificationRole": {
            "type": "boolean",
            "nullable": true
          },
          "menus": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/MenuItem"
            }
          }
        }
      },
      "MenuItem": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "url": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "info": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          },
          "orderNumber": {
            "type": "integer",
            "format": "int32"
          },
          "menuGroup": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/MenuGroup"
              }
            ]
          },
          "permissions": {
            "type": "array",
            "nullable": true,
            "items": {
              "type": "integer",
              "format": "int32"
            }
          },
          "enumMenuItem": {
            "$ref": "#/components/schemas/EnumMenuItem"
          }
        }
      },
      "MenuGroup": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "url": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "info": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          },
          "orderNumber": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "EnumMenuItem": {
        "type": "integer",
        "description": "",
        "x-enumNames": [
          "AdminCostSettings",
          "ApprovalGroups",
          "ApprovalStages",
          "ApprovalWorkflows",
          "CustomersDepartments",
          "Documents",
          "EquipmentMaintenance",
          "Financial",
          "FreeformQuote",
          "HelpPages",
          "Invoices",
          "Locations",
          "Monitors",
          "Operational",
          "Parts",
          "PendingApprovals",
          "ProcedureTypes",
          "PurchaseOrders",
          "Purchases",
          "QuotesProducts",
          "Reports",
          "RoleModulePermission",
          "RunnableProcedures",
          "SupportTicket",
          "Templates",
          "TrainingCertifications",
          "UserRoles",
          "Users",
          "WIPHistory",
          "WIPMenu",
          "WipStatus",
          "Roles"
        ],
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31
        ]
      },
      "UpdateMenuRoleMapRequest": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "menuRoleId": {
            "type": "integer",
            "format": "int32"
          },
          "canRead": {
            "type": "boolean"
          },
          "canCreate": {
            "type": "boolean"
          },
          "canEdit": {
            "type": "boolean"
          },
          "canDelete": {
            "type": "boolean"
          },
          "canActivate": {
            "type": "boolean"
          },
          "canApprove": {
            "type": "boolean"
          }
        },
        "example": {
          "menuRoleId": 1,
          "canRead": true,
          "canCreate": true,
          "canEdit": true,
          "canDelete": true,
          "canActivate": true,
          "canApprove": true
        }
      },
      "AuditActionResultOfICollectionOfUser": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "array",
                "nullable": true,
                "items": {
                  "$ref": "#/components/schemas/User"
                }
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "User": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "isActive": {
            "type": "boolean"
          },
          "userRoleId": {
            "type": "string",
            "nullable": true
          },
          "userName": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "securityStamp": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "supervisorId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "supervisorName": {
            "type": "string",
            "nullable": true
          },
          "locationId": {
            "type": "integer",
            "format": "int32"
          },
          "locationName": {
            "type": "string",
            "nullable": true
          },
          "isAnswerUser": {
            "type": "boolean"
          },
          "customerId": {
            "type": "integer",
            "format": "int32"
          },
          "lockoutEndDateUtc": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "lockoutEnabled": {
            "type": "boolean"
          },
          "accessFailedCount": {
            "type": "integer",
            "format": "int32"
          },
          "timeZoneId": {
            "type": "integer",
            "format": "int32"
          },
          "lastUpdatedOn": {
            "type": "string",
            "format": "date-time"
          },
          "lastUpdatedBy": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "createdOn": {
            "type": "string",
            "format": "date-time"
          },
          "createdBy": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "roles": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/Role"
            }
          }
        }
      },
      "AuditActionResultOfUser": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/User"
                  }
                ]
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "CreateUserRequest": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "userName": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "securityStamp": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "supervisorId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "locationId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "isActive": {
            "type": "boolean"
          },
          "isAnswerUser": {
            "type": "boolean",
            "nullable": true
          },
          "customerId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "lockoutEndDateUtc": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "lockoutEnabled": {
            "type": "boolean"
          },
          "accessFailedCount": {
            "type": "integer",
            "format": "int32"
          },
          "timeZoneId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "roles": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/Role"
            }
          }
        }
      },
      "UpdateUserRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CreateUserRequest"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        ],
        "example": {
            "id": 2147483647,
            "isActive": false
        }
      },
      "AuditActionResultOfPendingApprovalNotification": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/PendingApprovalNotification"
                  }
                ]
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "PendingApprovalNotification": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "customers": {
            "type": "integer",
            "format": "int32"
          },
          "locations": {
            "type": "integer",
            "format": "int32"
          },
          "parts": {
            "type": "integer",
            "format": "int32"
          },
          "procedures": {
            "type": "integer",
            "format": "int32"
          },
          "purchaseOrders": {
            "type": "integer",
            "format": "int32"
          },
          "users": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "AuditActionResultOfICollectionOfWorkflowGroupModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "array",
                "nullable": true,
                "items": {
                  "$ref": "#/components/schemas/WorkflowGroupModel"
                }
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "WorkflowGroupModel": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "lastUpdatedOn": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "lastUpdatedBy": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "lastUpdatedByName": {
            "type": "string",
            "nullable": true
          },
          "createdOn": {
            "type": "string",
            "format": "date-time"
          },
          "createdBy": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "createdByName": {
            "type": "string",
            "nullable": true
          },
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "isActive": {
            "type": "boolean"
          },
          "groupRoles": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/WorkflowGroupRoleMapModel"
            }
          }
        }
      },
      "WorkflowGroupRoleMapModel": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "roleId": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "workflowGroupId": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          }
        }
      },
      "AuditActionResultOfWorkflowGroupModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/WorkflowGroupModel"
                  }
                ]
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "CreateWorkflowGroupRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "isActive": {
            "type": "boolean"
          },
          "roles": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/WorkflowGroupRoleMapModel"
            }
          }
        },
        "example": {
            "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
            "isActive": true,
            "roles": [{
                "roleId": 2147483647,
                "name": "WorkflowGroupRoleMapModel-8faf6491cf88817e"
            }]
        }
      },
      "UpdateWorkflowGroupRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CreateWorkflowGroupRequest"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        ],
        "example": {
            "name": "CreateWorkflowGroupRequest-d416d136293debef",
            "isActive": true,
            "roles": [{
                "roleId": 2147483647,
                "name": "WorkflowGroupRoleMapModel-d416d136293debef"
            }],
            "id": 2147483647
        }
      },
      "AuditActionResultOfICollectionOfWorkflowStageModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "type": "array",
                "nullable": true,
                "items": {
                  "$ref": "#/components/schemas/WorkflowStageModel"
                }
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "WorkflowStageModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/DeletableModel"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "name": {
                "type": "string",
                "nullable": true
              },
              "lastUpdatedByName": {
                "type": "string",
                "nullable": true
              },
              "createdByName": {
                "type": "string",
                "nullable": true
              }
            }
          }
        ]
      },
      "DeletableModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/TrackableModel"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "isActive": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "TrackableModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/EntityModel"
          },
          {
            "type": "object",
            "x-abstract": true,
            "additionalProperties": true,
            "properties": {
              "lastUpdatedOn": {
                "type": "string",
                "format": "date-time",
                "nullable": true
              },
              "lastUpdatedBy": {
                "type": "integer",
                "format": "int32",
                "nullable": true
              },
              "createdOn": {
                "type": "string",
                "format": "date-time"
              },
              "createdBy": {
                "type": "integer",
                "format": "int32",
                "nullable": true
              }
            }
          }
        ]
      },
      "EntityModel": {
        "type": "object",
        "x-abstract": true,
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "AuditActionResultOfWorkflowStageModel": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AuditActionResult"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "object": {
                "nullable": true,
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/WorkflowStageModel"
                  }
                ]
              },
              "returnedObject": {
                "nullable": true
              }
            }
          }
        ]
      },
      "CreateWorkflowStageRequest": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "isActive": {
            "type": "boolean"
          }
        }
      },
      "UpdateWorkflowStageRequest": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CreateWorkflowStageRequest"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "type": "integer",
                "format": "int32"
              }
            }
          }
        ]
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "Copy this into the value field: Bearer {token}",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}
